language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe

env:
  matrix:
    - python=2.7  CONDA_PY=27  PYTHONPATH=/bin/modeller9.14/modlib:/bin/modeller9.14/lib/x86_64-intel8/python2.5  LD_LIBRARY_PATH=/bin/modeller9.14/lib/x86_64-intel8