language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++
      - gfortran
      - valgrind
      - csh
      - g++-multilib
      - gcc-multilib

branches:
  only:
    - master

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export CC=gcc
  - export CXX=g++

script:
  - conda config --add channels https://conda.binstar.org/omnia
  - conda build devtools/conda-recipe
  - source devtools/travis-ci/test.sh

env:
  global:
    # KEY_MODELLER for testing with modeller package
    secure: "IBRn//ZkrK6jRbt0sEsKKy3v95HNhejs7mYCqPRhAG/w2fRWaPIuKrR7VWbC3D1kIU7wCbUPkQNefB2CIPxiFA+rzJt1WTok4cNy4U4XhRpTXk4lm72u4+X1H1PSsJIOKd7PHxAv4bK9va2tsdt5WXViqx+/FgC61ZgnEvL/FOk="
    # BINSTAR_TOKEN
    secure: "KpipUgZIm+dJX9o+qMj237URs2M7FAm/hcl03mM/dcrNktf4k4w2fajTAdrx2Qk68eigQhg+oZZOCvX3eE+eFuUzBPFZfH2G+JaQBG4KDNwO83WYCL+tYDRf1Prlm7p4yYtGUpac2Um3RCBP6+sEE5R+UxQX0KdPoIH4nYfQ5j0="
  matrix:
    - python=2.7  CONDA_PY=27
    # - python=3.3  CONDA_PY=33
    # - python=3.4  CONDA_PY=34

after_success:
  - echo "after_success"
  - source devtools/travis-ci/after_success.sh
