language: c

branches:
  only:
    - master

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - source devtools/travis-ci/test.sh

env:
  global:
    secure: "FdnZE5EkkpZWvrLMSldJgbQTqmd8HtIAGHCJKQZR/zSOghmtKYhZelvBDMi/NX8dRVw7SbFhiUiQ8lK9Dv4XqufmA3dfLQMBtPgSIlvoLyWkxHbIQJJ5xTt5IgBXj+OKHhiEil5pvxtkt65C8NWWYZKc/LeabimyiXaxVuPvOIM="
  matrix:
    - python=2.7  CONDA_PY=27  PYTHONPATH=/home/travis/bin/modeller9.14/modlib:/home/travis/bin/modeller9.14/lib/x86_64-intel8/python2.5  LD_LIBRARY_PATH=/home/travis/bin/modeller9.14/lib/x86_64-intel8
    # - python=3.3  CONDA_PY=33  PYTHONPATH=/home/travis/bin/modeller9.14/modlib:/home/travis/bin/modeller9.14/lib/x86_64-intel8/python3.3  LD_LIBRARY_PATH=/home/travis/bin/modeller9.14/lib/x86_64-intel8
    # - python=3.4  CONDA_PY=34  PYTHONPATH=/home/travis/bin/modeller9.14/modlib:/home/travis/bin/modeller9.14/lib/x86_64-intel8/python3.3  LD_LIBRARY_PATH=/home/travis/bin/modeller9.14/lib/x86_64-intel8