language: c
sudo: false

branches:
  only:
    - master

env:
  global:
    - ORGNAME="omnia"
    - PACKAGENAME="ensembler"
    # KEY_MODELLER for testing with modeller package
    - secure: "M6Qw8y6+Q05+ciQ/JGxhO/3jmc/qtywy2xE4nGBIpDDMZ1FJH17tN1YVMMXM8Ld2DIFb/4CMGHKi03URfxdve9Q8QT9AMo+nffvHqrQizyX26ao3eAo61p0r0s7qLtAwymx2PoRvZxOOvZHpq11VN0gMeCynU4OPCf4nWZ9BbgE="
    # BINSTAR_TOKEN
    - secure: "KpipUgZIm+dJX9o+qMj237URs2M7FAm/hcl03mM/dcrNktf4k4w2fajTAdrx2Qk68eigQhg+oZZOCvX3eE+eFuUzBPFZfH2G+JaQBG4KDNwO83WYCL+tYDRf1Prlm7p4yYtGUpac2Um3RCBP6+sEE5R+UxQX0KdPoIH4nYfQ5j0="
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  # Add org channel
  - conda config --add channels ${ORGNAME}

script:
  # Create a test environment
  - conda create --yes -n test python=$python
  # Activate the test environment
  - source activate test
  # Add org channel
  - conda config --add channels ${ORGNAME}
  # Add omnia dev channels
  - conda config --add channels omnia/label/dev
  # Install extras for testing
  - conda install --yes --quiet pip nose nose-timer
  # Build the recipe
  - conda build devtools/conda-recipe
  # Install the package
  - conda install --yes --use-local ${PACKAGENAME}-dev
  # Test the package
  - cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer --exe -a unit -a modeller -a 'unit' -a '!slow' && cd ..

after_success:
  - echo "after_success"
  - source devtools/travis-ci/after_success.sh
