package:
  name: ensembler-dev
  version: 0.0.0

source:
   path: ../..

build:
  number: 0
  entry_points:
    - ensembler = ensembler.cli:main
  skip:
    - [win]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - modeller ==9.16
    - mdtraj
    - msmbuilder
    - biopython
    - openmm
    - pdbfixer ==1.2
    # - numpy
    - lxml
    - pyyaml
    - docopt
    - mock
    - subprocess32 # [py2k]
    - libgfortran ==1.0.0 [linux]

test:
  requires:
    - nose
  imports:
    - ensembler

about:
  home: https://github.com/choderalab/ensembler
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Pipeline for automating omics-scale protein modeling and simulation setup.
