package:
  name: ensembler
  version: !!str dev

#source:
#   git_url: https://github.com/choderalab/ensembler

build:
  preserve_egg_dir: True
  number: 0
  entry_points:
    - ensembler = ensembler.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - mpi4py
    - mdtraj
    - msmbuilder
    - biopython
    - openmm
    - pdbfixer
    - numpy
    - lxml
    - pyyaml
    - docopt
    - mock
    - subprocess32 # [py2k]

test:
  requires:
    - nose
  imports:
    - ensembler
  commands:
    - nosetests ensembler -v --exe -a unit

about:
  home: https://github.com/choderalab/ensembler
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Pipeline for automating omics-scale protein modeling and simulation setup.
