package:
  name: ensembler
  version: !!str dev

source:
   git_url: https://github.com/choderalab/ensembler

build:
  entry_points:
    - EnsemblerInit = ensembler.scripts.EnsemblerInit:main
    - EnsemblerGatherTargets = ensembler.scripts.EnsemblerGatherTargets:main
    - EnsemblerGatherTemplates = ensembler.scripts.EnsemblerGatherTemplates:main
    - EnsemblerBuildModels = ensembler.scripts.EnsemblerBuildModels:main
    - EnsemblerRefineImplicitMD = ensembler.scripts.EnsemblerRefineImplicitMD:main
    - EnsemblerSolvate = ensembler.scripts.EnsemblerSolvate:main
    - EnsemblerRefineExplicitMD = ensembler.scripts.EnsemblerRefineExplicitMD:main
    - EnsemblerPackage = ensembler.scripts.EnsemblerPackage:main

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - mpi4py
    - mdtraj
    - biopython
    - openmm
    - numpy
    - lxml
    - pyyaml

about:
  home: https://github.com/choderalab/ensembler
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
