package:
  name: msmseeder
  version: !!str dev

source:
   git_url: https://github.com/choderalab/msmseeder

build:
  entry_points:
    - MSMSeederInit = mdtraj.scripts.MSMSeederInit:main
#     - MSMSeederGatherTargets.py = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/choderalab/msmseeder
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
