package:
  name: ensembler
  version: !!str dev

source:
   git_url: https://github.com/choderalab/ensembler

build:
  entry_points:
    - ensembler = ensembler.cli:main

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - mpi4py
    - mdtraj
    - biopython
    - openmm
    - numpy
    - lxml
    - pyyaml
    - subprocess32

about:
  home: https://github.com/choderalab/ensembler
  license: GNU Lesser General Public License v2 or later (LGPLv2+)