package:
  name: msmseeder
  version: !!str dev

source:
   git_url: https://github.com/choderalab/msmseeder

build:
  entry_points:
    - MSMSeederInit = msmseeder.scripts.MSMSeederInit:main
    - MSMSeederGatherTargets = msmseeder.scripts.MSMSeederGatherTargets:main
    - MSMSeederGatherTemplates = msmseeder.scripts.MSMSeederGatherTemplates:main
    - MSMSeederBuildModels = msmseeder.scripts.MSMSeederBuildModels:main
    - MSMSeederRefineImplicitMD = msmseeder.scripts.MSMSeederRefineImplicitMD:main
    - MSMSeederSolvate = msmseeder.scripts.MSMSeederSolvate:main
    - MSMSeederRefineExplicitMD = msmseeder.scripts.MSMSeederRefineExplicitMD:main
    - MSMSeederPackage = msmseeder.scripts.MSMSeederPackage:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - mpi4py
    - mdtraj
    - biopython
    - openmm
    - numpy
    - lxml
    - yaml

about:
  home: https://github.com/choderalab/msmseeder
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
